### ISSUE TITLE
Adding Multiple Arrays of Listeners Does Not Work

### ISSUE THREAD

**Issue by Akamaozu** [shalvah/burns#1]
![image](https://user-images.githubusercontent.com/1587024/31841893-94090438-b5b9-11e7-8393-689572ff8382.png)

![image](https://user-images.githubusercontent.com/1587024/31841925-b297f6a2-b5b9-11e7-9c55-96a9747daf45.png)

**Comment by shalvah** [comment]
Thanks for this @akamaozu. Could you check that you're on version 1.0.10?

**Comment by Akamaozu** [comment]
@shalvah ![image](https://user-images.githubusercontent.com/1587024/31843685-81e073aa-b5c2-11e7-849a-81a5742565d0.png)

**Comment by shalvah** [comment]
Thanks for this @Akamaozu . Found and fixed the bug in release 1.0.11. You can update your package now, and all should be well :slightly_smiling_face:
